name: Test Conditional Workflow
on:
  workflow_dispatch:
jobs:
  Build_and_Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/Checkout@v3
      - name: Install Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
      - name: Run Test
        #Step Id to be used by other steps to access the step outcomes.
        id: gradle-build
        run: ./gradlew run test
      - name: Run on Failure
        #Based on the outcome of the step with ID: gradle-build, the Run on Failure step runs else will be omitted.
        if: failure() && steps.gradle-build.outcome == 'failure'
        run: echo "Test Execution Failed! Entering Conditional Workflow Step"
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "Deploying...."
      - name: Run If Success
        if: success()
        run: echo " Workflow executed successfully!!"
      - name: Run Always
        if: always()
        run: echo "always() conditional function tested!!"
  Cancel_Workflow:
    runs-on: ubuntu-latest
    needs: Deploy
    #Runs the workflow when the deploy job is cancelled
    if: cancelled()
    steps:
      - name: Test Cancel
        run: echo "Cancelled() executed when workflow is cancelled"
  Always_Workflow:
    runs-on: ubuntu-latest
    needs: Deploy
    #Runs the workflow irrespective of the workflow status.
    if: always()
    steps:
      - name: Test Always
        run: echo "Always() executed even when workflow is cancelled/not cancelled"
