name: Testing JavaScript Action
on: workflow_dispatch

jobs:
  run_javascript_action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/Checkout@v3
      - name: Run JavaScript Action
        id: js_action
        uses: ./.github/actions/javascript-action
        with:
          user: Maneesh Murali
      - name: Receive Output
        run: |
          echo "Response From Js Action: ${{steps.js_action.outputs.response}}"