name: Pull Request
on:
  pull_request:
    #Branches for which the Build has to be triggered
    branches:
      - main
    #Activity types for which the PR build has to be triggered
    types:
      - opened
jobs:
  PR_Build:
    runs-on: ubuntu-latest
    steps:
      - name: Build PR
        run: echo "Building Pull Request"
